### ISSUE TITLE
Blazor + ProtobufMarshallerFactory

### ISSUE THREAD

**Issue by FireSon** [max-ieremenko/ServiceModel.Grpc#29]
**Describe the bug**
When I try to use the combination Blazor (from the examples)+ ProtobufMarshallerFactory there is an error during the service call:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at ServiceModel.Grpc.Client.ClientChannelAdapter.<GetAsyncUnaryCallResult>d__1`1[[System.Collections.Generic.IList`1[[BlazorApp.Shared.WeatherForecast, BlazorApp.Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at BlazorApp.Client.Pages.FetchData.Reload() in C:\Application\Its-Hub\ServiceModel.Grpc-master\Examples\BlazorApp\BlazorApp\Client\Pages\FetchData.razor:line 53
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**To Reproduce**
I modified the Blazor example 
In the client program.cs I added:
            services.AddSingleton<IClientFactory>(_ => new ClientFactory(new ServiceModelGrpcClientOptions
            {
                MarshallerFactory = ProtobufMarshallerFactory.Default
            }));

In the server startup.cs I added:
            services.AddServiceModelGrpc(options => options.DefaultMarshallerFactory = ProtobufMarshallerFactory.Default);

What could be the problem?
Thanks!

**Comment by FireSon** [comment]
Oeps, sorry I forgot to add the [ProtoMember(1)] attributes, my bad :-)
