### ISSUE TITLE
Authentication with AzureAD error

### ISSUE THREAD

**Issue by FireSon** [max-ieremenko/ServiceModel.Grpc#30]
There is an error: ` Grpc.Core.RpcException: 'Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; `
when using a Blazor ServerSide App with AzureAd authentication. When I change the authentication in this App to exactly the  same JwtBearer security from the AspNetCoreAuthenticationTestBase.cs test everything works perfectly. However switching to AzureAD with the following settings:
 ```
           services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                {
                    Configuration.Bind("AzureAd", options);
                    options.ResponseType = "code";
                    options.SaveTokens = true;
                });
```
 
gives the error, although the specified Token is correct. If I use the exact same authentication settings in a WASM Blazor app everything works fine. Also if I remove the Authorize attribute from the service everything works fine. In order to exclude possibilities I also tested the same application with Protobuf-Grpc and then the exact same exception is thrown. 
I am aware that it is a bit 'strange' to use gRPC in this scenario (serverside blazor), but basically I am trying to debug my application serverside because of the better "debug experience". 

The browser logging looks like:
```
Grpc.Core.RpcException: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: text/html; charset=utf-8")
   at ServiceModel.Grpc.Client.ClientChannelAdapter.GetAsyncUnaryCallResult[T](AsyncUnaryCall`1 call, CallContext context, CancellationToken token)
   at QatramApp.Pages.FetchData.Reload() in C:\Application\DevQatram\QatramApp\Pages\FetchData.razor:line 54
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

The client is created in this way:
```
  var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler()));
  var credentials = CallCredentials.FromInterceptor(async (context, metadata) =>
      metadata.Add("Authorization", $"Bearer {Token}"));
  Channel = GrpcChannel.ForAddress(navigationManager.BaseUri, Options = new GrpcChannelOptions
  {
      HttpClient = httpClient,
      Credentials = ChannelCredentials.Create(new SslCredentials(), credentials)
  });

  clientFactory = new ClientFactory(new ServiceModelGrpcClientOptions { MarshallerFactory = ProtobufMarshallerFactory.Default });
  var client = clientFactory.CreateClient<T>(Channel);

```

Any thoughts??
Thanks!
Jan

**Comment by FireSon** [comment]
I did some more testing and I think it has to do with Grpc.Net.Client.Web, i will ask the question there!
Thanks!
