### ISSUE TITLE
gRPC client throws the following exception when trying to invoke the proxy stub code.

### ISSUE THREAD

**Issue by dannypang** [max-ieremenko/ServiceModel.Grpc#32]
I got the following exception using the design time client connecting to a self-hosting gRPC service,
It seems that the server didn't even connect and the client throws the following exception can you please let me know how to deal with it?

Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1620792359.173000000","description":"Error received from peer ipv6:[::1]:8090","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Exception was thrown by handler.","grpc_status":2}")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceModel.Grpc.Client.ClientChannelAdapter.<GetAsyncUnaryCallResult>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squid.InstantMessage.DesignTime.Program.<CallSquare>d__3.MoveNext() in C:\Users\danny\RiderProjects\TheSquid_Master\Squid.InstantMessage.DesignTime\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Squid.InstantMessage.DesignTime.Program.<Main>d__1.MoveNext() in C:\Users\danny\RiderProjects\TheSquid_Master\Squid.InstantMessage.DesignTime\Program.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Squid.InstantMessage.DesignTime.Program.<Main>()

**Comment by max-ieremenko** [comment]
hello @dannypang,

could you please share the code, from existing stack trace i can only guess that an exception is being thrown in your server code.

**Comment by dannypang** [comment]
I have resolved the issue. It seems that the server side somehow silently ignore the unity being not able to construct an object. There is no exception being thrown. It took me a full day to debug it. Now it is okay. Please ignore the issue. 

Thanks for contributing to the open source gRPC code first. I'd appreciate it.
