### ISSUE TITLE
Silent exception happen on the gRPC server side.

### ISSUE THREAD

**Issue by dannypang** [max-ieremenko/ServiceModel.Grpc#33]
Hi 

I've tried again today to run the GRPC service model. I noticed that it could be failing on the server side with the call stack below:

I am trying to implement  and debug the problem and my server side implementation is like the following;
// I tried to add a wait loop here. but it never stop in the sleep mode and go directly to exit the function. 
// Hence I believe that it is failing with a silent exception, can you help?

public async IAsyncEnumerable<IEnumerable<MessageDetail_RevCon>> GetMessageDetailAsyncEnumerable(DateTime start, DateTime end)
        {
            await foreach (var formatMessageItems in GetFormattedMessagesAsyncEnumerable(start, end))
            {
                var messageDetails = new List<MessageDetail_RevCon>();
                foreach (var formatMessageItem in formatMessageItems)
                {
                    var conversionItem = _conversionItemFactory.GetConversionItem(formatMessageItem);
                    if(conversionItem != null && conversionItem is MessageDetail_RevCon)
                    {
                        messageDetails.Add( (MessageDetail_RevCon)conversionItem);
                    }
                }
                yield return messageDetails.AsEnumerable();
            }

// I tried to add a wait loop here. but it never stop in the sleep mode and go directly to exit the function. 
// Hence I believe that it is failing with a silent exception, can you help?
            while(true)
                System.Threading.Thread.Sleep(500);
        }

Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1621284891.042000000","description":"Error received from peer ipv6:[::1]:8090","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Exception was thrown by handler.","grpc_status":2}")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ServiceModel.Grpc.Client.ClientChannelAdapter.<GetServerStreamingCallResult>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at ServiceModel.Grpc.Client.ClientChannelAdapter.<GetServerStreamingCallResult>d__2`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Squid.InstantMessage.ClientApp.Program.<TestGetMessageDetailAsyncEnumerable>d__2.MoveNext() in C:\Users\danny\RiderProjects\TheSquid_Master\Squid.InstantMessage.ClientApp\Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squid.InstantMessage.ClientApp.Program.<TestGetMessageDetailAsyncEnumerable>d__2.MoveNext() in C:\Users\danny\RiderProjects\TheSquid_Master\Squid.InstantMessage.ClientApp\Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Squid.InstantMessage.ClientApp.Program.<Main>d__1.MoveNext() in C:\Users\danny\RiderProjects\TheSquid_Master\Squid.InstantMessage.ClientApp\Program.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Squid.InstantMessage.ClientApp.Program.<Main>()

**Comment by max-ieremenko** [comment]
hi @dannypang,

in the provided code i do not see issues.
Could you please share the project/solution? 
At least client code with call, server set-up (Startup.cs) and MessageDetail_RevCon.

**Comment by dannypang** [comment]
Can you tell me how can you turn on server side debug logging?

**Comment by max-ieremenko** [comment]
Since the original poster hasn`t yet responded to the request made to them month ago, I am closing this issue.
I assume that the user has lost interest or resolved the problem on their own.
If this in error, let me know with a comment and I will be happy to reopen the issue.
