### ISSUE TITLE
Blazor File upload gives exception

### ISSUE THREAD

**Issue by FireSon** [max-ieremenko/ServiceModel.Grpc#37]
**Describe the bug**
When I try to upload an image file with an IAsyncEnumerable<byte[]> call there is an "Unexpected end of data when reading base64 content" error message.

**To Reproduce**
See attachement, this is the Blazor example with code to upload a file in the index.razor.
[test.zip](https://github.com/max-ieremenko/ServiceModel.Grpc/files/6734454/test.zip)

It seems that the async/await is not properly synchronized. 
The upload was based upon an (partly) example of https://github.com/max-ieremenko/ServiceModel.Grpc/issues/18 
Any help would be greatly appreciated!

**Comment by max-ieremenko** [comment]
Depending on the uploaded image size, the attached implementation may not work.

GetFileAsync in Index.razor, see my comments:

``` c#
while (bytesRead < content.Length)
{
	var bytesToRead = content.Length - bytesRead;
	var buffer = new byte[Math.Min(bufferSize, bytesToRead)];

	// the result of ReadAsync can be less than the number of bytes allocated in the buffer: (reallyRead != buffer.Length)
	var reallyRead = await content.ReadAsync(buffer, 0, buffer.Length);

	yield return buffer;
	bytesRead += bufferSize;
}
```

your example with changes:

``` c#
private static async IAsyncEnumerable<byte[]> GetFileAsync(System.IO.Stream content)
{
	const int maxBufferSize = 4 * 1024;
	int totalBytesRead = 0;

	while (totalBytesRead < content.Length)
	{
		var bufferSize = (int)Math.Min(content.Length - totalBytesRead, maxBufferSize);
		var buffer = new byte[bufferSize];

		var bufferOffset = 0;
		while (bufferOffset != bufferSize)
		{
			var length = await content.ReadAsync(buffer, bufferOffset, bufferSize - bufferOffset);
			bufferOffset += length;
		}

		yield return buffer;
		totalBytesRead += bufferSize;
	}

	Console.WriteLine("Ready");
}
```

**Comment by FireSon** [comment]
Hi Max,

Thanks for the quick response, and solution! I never considered that the number of bytes could not match the number requested but you are right about that. Unfortunately I also tested a version where I read all the bytes of the file into a memory stream and used that to send chunks to the server and that version had the same error message. I just tested your solution as well and unfortunately that produced the same error. 
The file I use for testing is the MicrosoftTeams-image.png located in the wwwroot directory of the client.

Could there be some other error?
Thanks for your time!!
Cheers

I do not know if it helps but this is the stacktrace of the error

```
System.InvalidOperationException: Unexpected end of data when reading base64 content.
   at Grpc.AspNetCore.Web.Internal.Base64PipeReader.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
'BlazorApp.Server.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Grpc.AspNetCore.Server.ServerCallHandler: Error: Error when executing service method 'UploadFile'.

System.InvalidOperationException: Unexpected end of data when reading base64 content.
   at Grpc.AspNetCore.Web.Internal.Base64PipeReader.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.<MoveNext>g__MoveNextAsync|9_0(ValueTask`1 readStreamTask)
   at ServiceModel.Grpc.Hosting.ServerChannelAdapter.ReadClientStream[T](IAsyncStreamReader`1 stream, ServerCallContext context)+MoveNext()
   at ServiceModel.Grpc.Hosting.ServerChannelAdapter.ReadClientStream[T](IAsyncStreamReader`1 stream, ServerCallContext context)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at BlazorApp.Server.Services.WeatherForecastService.UploadFile(IAsyncEnumerable`1 content, CancellationToken token) in C:\Application\test\TestStream\BlazorApp\Server\Services\WeatherForecastService.cs:line 58
   at BlazorApp.Server.Services.WeatherForecastService.UploadFile(IAsyncEnumerable`1 content, CancellationToken token) in C:\Application\test\TestStream\BlazorApp\Server\Services\WeatherForecastService.cs:line 58
   at ServiceModel.Grpc.Hosting.ServerChannelAdapter.UnaryCallWaitTask(Task call)
   at Grpc.Shared.Server.ClientStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream)
   at Grpc.Shared.Server.ClientStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, IAsyncStreamReader`1 requestStream)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ClientStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HM9S1DQN2SCF", Request id "0HM9S1DQN2SCF:00000006": An unhandled exception was thrown by the application.

Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.VerifyIsNotReading()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
   --- End of inner exception stack trace ---
Uncaught Error: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")The thread 0x0 has exited with code 0 (0x0).
The program 'JavaScript debug adapter: localhost:5000' has exited with code -1 (0xffffffff).
The program '' has exited with code -1 (0xffffffff).
The program '[1952] BlazorApp.Server.exe: Program Trace' has exited with code 0 (0x0).
The program '[1952] BlazorApp.Server.exe' has exited with code -1 (0xffffffff).

````

**Comment by max-ieremenko** [comment]
hi @FireSon,

yep, when i tested my .png was less then 4096 - client streaming with one `yield return buffer` works.

There is a nice [gRPC-Web limitation](https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0#grpc-web-and-streaming):
> gRPC-Web browser clients don't support calling client streaming and bidirectional streaming methods.
> When using gRPC-Web, we only recommend the use of unary methods and server streaming methods.

workaround, but with LOH allocations (can be improved):
``` c#
[ServiceContract]
public interface IService
{
	[OperationContract]
	Task UploadFile(byte[] file);
}

var resizedFile = await imageFile.RequestImageFileAsync("image/png", 300, 500);
using (var content = resizedFile.OpenReadStream(resizedFile.Size))
{
	var buffer = new MemoryStream();
	await content.CopyToAsync(buffer);
	
	await Service.UploadFile(buffer.ToArray());
}
```

or use pure asp.net (client/server)
``` c#
public class TestController : Controller
{
	[HttpPost]
	public Task UploadFile(Stream stream)
	{
		// TODO ..
	}
}
```

**Comment by FireSon** [comment]
Hi Max,
Thanks for the help. I was afraid it would be something like that, since I used basically the same code successfully in a none web environment.
Cheers
